export const enum buttonsName {
  ADD = 'add',
  CANCEL = 'cancel',
  SIGN_IN = 'sign in',
  REGISTER = 'register',
  SAVE = 'save',
  GO_AHEAD = 'go ahead',
  DONATE = 'donate',
  ADOPT = 'adopt',
  ADD_PET = 'add pet',
  CLEAR = 'clear',
  SEND = 'send',
  BACK = 'back',
  RELOAD = 'reload',
  PAY = 'pay',
}
