export const enum iconsName {
  ATTACH = 'attach',
  ATTACH_OUTLINE = 'attach-outline',
  CHATBOX = 'chatbox',
  CHATBOX_OUTLINE = 'chatbox-outline',
  CALENDAR_OUTLINE = 'calendar-outline',
  CALENDAR = 'calendar',
  CREATE_OUTLINE = 'create-outline',
  CLIPBOARD_OUTLINE = 'clipboard-outline',
  ADD = 'add',
  PAW = 'paw',
  PAW_OUTLINE = 'paw-outline',
  MAP_OUTLINE = 'map-outline',
  MAP = 'map',
  CAT = 'cat',
  UNKNOWN = 'male-female-outline',
  BOY = 'male-outline',
  GIRL = 'female-outline',
  LOG_OUT_OUTLINE = 'log-out-outline',
  EYE = 'eye',
  EYE_OFF = 'eye-off',
  PEOPLE = 'people',
  PEOPLE_OUTLINE = 'people-outline',
}
