export const enum iconsName {
  PERSON = 'person',
  PERSON_OUTLINE = 'person-outline',
  ATTACH = 'attach',
  ATTACH_OUTLINE = 'attach-outline',
  CHATBOX = 'chatbox',
  CHATBOX_OUTLINE = 'chatbox-outline',
  ADD_OUTLINE = 'add-outline',
  CALENDAR_OUTLINE = 'calendar-outline',
  CALENDAR = 'calendar',
  CREATE_OUTLINE = 'create-outline',
  CLIPBOARD_OUTLINE = 'clipboard-outline',
  ADD = 'add',
  PAW = 'paw',
  EARTH_OUTLINE = 'earth-outline',
  EARTH = 'earth',
  CAT = 'cat',
  UNKNOWN = 'male-female-outline',
  BOY = 'male-outline',
  GIRL = 'female-outline',
  LOG_OUT_OUTLINE = 'log-out-outline',
  EYE = 'eye',
  EYE_OFF = 'eye-off',
  PEOPLE = 'people',
  PEOPLE_OUTLINE = 'people-outline',
  SETTINGS = 'settings',
  SETTINGS_OUTLINE = 'settings-outline',
}
