export const enum iconsName {
  PERSON = 'person',
  PERSON_OUTLINE = 'person-outline',
  HOME = 'home',
  HOME_OUTLINE = 'home-outline',
  PEOPLE = 'people',
  PEOPLE_OUTLINE = 'people-outline',
  CHATBOX = 'chatbox',
  CHATBOX_OUTLINE = 'chatbox-outline',
  SHOPPING = 'shopping',
  SHOPPING_OUTLINE = 'shopping-outline',
  HOSPITAL_BOX = 'hospital-box',
  HOSPITAL_BOX_OUTLINE = 'hospital-box-outline',
  ACCOUNT_SUPERVISOR = 'account-supervisor',
  ACCOUNT_SUPERVISOR_OUTLINE = 'account-supervisor-outline',
}
