export const enum inputsPlaceholdersName {
  EMAIL = 'Enter your email',
  PASSWORD = 'Enter your password',
  NICK_NAME = 'Enter your name',
  ADD_TITLE = 'Add title',
  ADD_INFO = 'Add info',
  ADD_ADDRESS = 'Add address',
  PET_NICK_NAME = 'Name',
  PET_DESCRIPTION = 'Color',
  PET_OWNER_INFO = 'Telephone',
  PET_AGE = 'Date of birth',
  PET_BREED = 'Breed',
  PET_CHIP_ID = 'Chip id',
  CODE = 'Enter your code',
}
