export const GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN';
export const GOOGLE_SIGN_OUT = 'GOOGLE_SIGN_OUT';
export const ADD_NEW_PET = 'ADD_NEW_PET';
export const FETCH_PETS = 'FETCH_PETS';
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const GOOGLE_REGISTER = 'GOOGLE_REGISTER';
